name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.5.6
  geolocator: ^10.0.0
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/profile_placeholder.png
    - assets/landing.png
    - assets/arav.png
    - assets/aditya.png
    - assets/ridhima.png
    - assets/ray.png
    - assets/anjum.png
    - assets/ritika.png
    - assets/nidhi.png
    - assets/nikhil.png
    - assets/devinder.png
    - assets/krish.png
    - assets/mritunjay.png
    - assets/kavish.png
    - assets/yashika.png
    - assets/parmeet.png
    
  


